name: PR Test

on:
  pull_request:
    branches: [ master ] # master branch에 PR을 보낼 때 실행

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: compile test file
        run: javac -d out/test -cp ./lib/junit-platform-console-standalone-1.8.1.jar ./test/**/*.java

      - name: test junit
        run: java -jar ./lib/junit-platform-console-standalone-1.8.1.jar --class-path out/test --include-classname='.*'  --scan-class-path --reports-dir=out/test-results

      - name: code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          files: out/test-results/**/*.xml
          flags: unittests # optional
          name: codecov-umbrella # optional
          verbose: true # optional (default = false)
