name: PR Test

on:
  pull_request:
    branches: [ master ] # master branch에 PR을 보낼 때 실행

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16

      # Gradle test를 실행한다
      - name: compile test file
        run: javac -d out/test -cp ./lib/junit-platform-console-standalone-1.8.1.jar ./test/testPackage/MyClassTest.java

      - name: test junit
        run: java -jar ./lib/junit-platform-console-standalone-1.8.1.jar --class-path out/test --scan-class-path
